//! dspy `majority` (`predict/aggregation.py`): several answers to one question, reconciled.
//!
//! Three details decide the answer and each is easy to get wrong in the other direction. The
//! field read is the *last* one rather than the first. Normalising happens before counting, not
//! after, so two spellings of one answer are one vote. And a tie keeps the value seen earliest,
//! which is what Python's `max` over a dict does and the opposite of what `max_by_key` does.
//!
//! Held to `tests/conformance/predict/aggregation.json`, generated by running dspy.

use std::collections::BTreeMap;

use anyhow::{Result, anyhow};

// The definition lives with dspy's, in `evaluate/metrics.py`; re-exported here because
// `majority` normalises before it counts, and callers reached it by this path first.
pub use crate::evaluate::metrics::normalize_text;
use crate::example::Example;

/// How a value is compared with another before the votes are counted.
///
/// Upstream spells this one parameter with three meanings, and the difference is not cosmetic:
/// left out it drops a completion whose value normalises to nothing, which is why an answer of
/// "a" disappears — the article is stripped and nothing remains.
pub enum Normalize {
    /// dspy's `default_normalize`: [`normalize_text`], and nothing left means no vote at all.
    Default,
    /// dspy's `normalize=None`: the value as written.
    AsWritten,
    /// dspy's `normalize=normalize_text`: normalised, but an empty result still votes.
    Text,
}

impl Normalize {
    fn apply(&self, value: &str) -> Option<String> {
        match self {
            Normalize::AsWritten => Some(value.to_owned()),
            Normalize::Text => Some(normalize_text(value)),
            Normalize::Default => match normalize_text(value) {
                empty if empty.is_empty() => None,
                normalized => Some(normalized),
            },
        }
    }
}

/// The completion holding the most common value of one field.
///
/// `field` names which one to read; without it the last field of the first completion is used,
/// which is upstream's rule for a signature it cannot see.
pub fn majority(
    completions: &[Example],
    normalize: &Normalize,
    field: Option<&str>,
) -> Result<Example> {
    let first = completions
        .first()
        .ok_or_else(|| anyhow!("majority needs at least one completion to read"))?;
    let field = match field {
        Some(field) => field.to_owned(),
        None => last_field(first)?,
    };

    let normalized: Vec<Option<String>> = completions
        .iter()
        .map(|completion| normalize.apply(&text(completion, &field)))
        .collect();
    let winner = most_common(&normalized);

    // The first completion whose value matches. Upstream leaves its loop variable behind after
    // the match, so a value nothing matches yields the *last* completion rather than an error —
    // reachable only when every value normalised away and the count fell back to those.
    let at = normalized.iter().position(|value| *value == winner);
    Ok(completions[at.unwrap_or(completions.len() - 1)].clone())
}

/// The value with the most votes, keeping the earliest on a tie.
///
/// Counting the un-normalised list when every value dropped out is upstream's fallback: it means
/// a set of answers that all normalise to nothing still elects one rather than failing.
fn most_common(normalized: &[Option<String>]) -> Option<String> {
    let counted: Vec<&Option<String>> = match normalized.iter().any(Option::is_some) {
        true => normalized.iter().filter(|value| value.is_some()).collect(),
        false => normalized.iter().collect(),
    };

    let mut counts: BTreeMap<&Option<String>, usize> = BTreeMap::new();
    let mut order: Vec<&Option<String>> = Vec::new();
    for value in counted {
        if counts
            .insert(value, counts.get(value).unwrap_or(&0) + 1)
            .is_none()
        {
            order.push(value);
        }
    }
    // Walked in first-seen order and replaced only on a strict `>`, so the earliest value wins a
    // tie. `max_by_key` keeps the *last* maximum and would elect the opposite; iterating the map
    // would break the tie by sort order instead of by arrival.
    order
        .into_iter()
        .reduce(|best, value| match counts[value] > counts[best] {
            true => value,
            false => best,
        })
        .cloned()
        .flatten()
}

fn last_field(completion: &Example) -> Result<String> {
    completion
        .fields()
        .map(|(name, _)| name.to_owned())
        .last()
        .ok_or_else(|| anyhow!("a completion with no fields has nothing to vote on"))
}

fn text(completion: &Example, field: &str) -> String {
    completion
        .get(field)
        .map(|value| match value.as_str() {
            Some(text) => text.to_owned(),
            None => value.to_string(),
        })
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    use serde_json::Value;

    fn golden() -> Value {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/conformance/predict/aggregation.json");
        let text = std::fs::read_to_string(&path).expect("the aggregation golden is committed");
        serde_json::from_str(&text).expect("the golden parses")
    }

    #[test]
    fn normalizes_the_text_dspy_normalizes() {
        for case in golden()["normalize_text"].as_array().expect("cases") {
            let text = case["text"].as_str().expect("a text");
            let expected = case["normalized"].as_str().expect("a result");
            assert_eq!(normalize_text(text), expected, "normalize_text({text:?})");
        }
    }

    /// Every vote dspy was asked to settle, including the two where a tie decides it.
    #[test]
    fn elects_the_completion_dspy_elects() {
        for case in golden()["majority"].as_array().expect("cases") {
            let completions: Vec<Example> = case["completions"]
                .as_array()
                .expect("completions")
                .iter()
                .map(|fields| {
                    Example::new(
                        fields
                            .as_object()
                            .expect("a completion")
                            .iter()
                            .map(|(name, value)| (name.as_str(), value.clone())),
                    )
                })
                .collect();
            let normalize = match case["normalize"].as_str().expect("a mode") {
                "default" => Normalize::Default,
                "identity" => Normalize::AsWritten,
                "text" => Normalize::Text,
                other => panic!("the golden names an unknown mode {other:?}"),
            };
            let field = case["field"].as_str();

            let winner = majority(&completions, &normalize, field).expect("elects");
            let expected = case["winner"].as_object().expect("a winner");
            for (name, value) in expected {
                assert_eq!(
                    winner.get(name),
                    Some(value),
                    "field {name} of the winner for {:?}",
                    case["completions"]
                );
            }
        }
    }
}
