//! dspy `MultiChainComparison` (`predict/multi_chain_comparison.py`): several students answer,
//! and the model is shown their working before it answers itself.
//!
//! The module is two edits to a signature and one string format, and each has a plausible wrong
//! version. The M attempt fields are appended to the *inputs* and numbered from 1 while the loop
//! counting them runs from 0. The corrected-reasoning field is *prepended* to the outputs, so the
//! model reasons before it answers — appending it would put the answer first and waste the
//! reasoning. And the caller's own inputs are merged over the attempts rather than under them,
//! so passing `reasoning_attempt_2` yourself replaces the one built for you.
//!
//! Upstream's own test asserts on none of that: it checks two parsed fields of a canned reply.
//! `tests/conformance/predict/mcc.json`, generated by running dspy, is the only oracle for the
//! bytes, and it carries the whole rendered message rather than the pieces.
//!
//! One recorded literal never reaches a model. dspy 3.2.1 deprecated `prefix=` on a field — the
//! value is still stored and still compared by `Signature.equals`, but no adapter reads it — so
//! `Student Attempt #1:` and `Accurate Reasoning: Thank you everyone. Let's now holistically`
//! are absent from every prompt dspy renders, and this crate has nowhere to keep them.

use anyhow::{Result, anyhow};
use serde_json::Value;

use super::{Dynamic, Predict};
use crate::adapter::python_json::format_value;
use crate::example::{Example, Prediction};
use crate::module::{Module, NamedPredictor, TraceStep};
use crate::signature::{InField, OutField, Signature};

/// dspy's `M`: how many attempts the module is built to compare.
const ATTEMPTS: usize = 3;

/// dspy.MultiChainComparison: compare several attempts at one task, then answer it again.
pub struct MultiChainComparison {
    predict: Predict,
    attempts: usize,
    /// The field an attempt's prediction is read from — the last output of the signature as it
    /// arrived, which is why it is captured before `rationale` is prepended to that list.
    last_key: String,
}

impl MultiChainComparison {
    /// A module comparing three attempts, which is dspy's default `M`.
    pub fn from_signature(signature: Signature) -> Result<Self> {
        Self::with_attempts(signature, ATTEMPTS)
    }

    /// The same, told how many attempts it will be given.
    ///
    /// Fails on a signature with no output fields, where there is no last field for an attempt's
    /// prediction to be read from. Upstream fails here too, on the tuple unpacking that looks
    /// for one.
    pub fn with_attempts(mut signature: Signature, attempts: usize) -> Result<Self> {
        let last_key = signature
            .outputs
            .last()
            .map(|field| field.name.clone())
            .ok_or_else(|| anyhow!("a signature with no output fields has no answer to compare"))?;

        for index in 1..=attempts {
            signature.inputs.push(InField {
                name: attempt_field(index),
                // Literal, not a template: dspy writes `${reasoning attempt}` where the field is
                // named `reasoning_attempt_1`, and the suppression that drops a description
                // echoing its own field name therefore misses. The model reads the braces.
                desc: "${reasoning attempt}".into(),
                ..Default::default()
            });
        }
        signature.outputs.insert(
            0,
            OutField {
                name: "rationale".into(),
                desc: "${corrected reasoning}".into(),
                ..Default::default()
            },
        );

        Ok(Self {
            predict: Predict::<Dynamic>::from_signature(signature),
            attempts,
            last_key,
        })
    }

    /// Show the model these attempts alongside the task's own inputs, and ask it again.
    ///
    /// The door into this module: `completions` are what the earlier attempts answered, and
    /// `inputs` is the request they were all answering.
    pub async fn compare(&self, completions: &[Example], inputs: Example) -> Result<Prediction> {
        self.predict
            .forward(self.asking(completions, inputs)?)
            .await
    }

    /// The inputs one comparison is asked with: an attempt per completion, then the caller's own.
    fn asking(&self, completions: &[Example], inputs: Example) -> Result<Example> {
        // Every attempt is formatted before the count is checked, so a completion missing its
        // reasoning is reported as that rather than as a miscount. Upstream orders it the same
        // way, and the two failures read very differently to whoever has to act on one.
        let formatted: Vec<String> = completions
            .iter()
            .map(|completion| self.attempt(completion))
            .collect::<Result<_>>()?;
        if formatted.len() != self.attempts {
            return Err(anyhow!(
                "The number of attempts ({}) doesn't match the expected number M ({}). \
                 Please set the correct value for M when initializing MultiChainComparison.",
                formatted.len(),
                self.attempts
            ));
        }

        let mut asking = Example::new(
            formatted
                .into_iter()
                .enumerate()
                .map(|(index, attempt)| (attempt_field(index + 1), Value::String(attempt))),
        );
        // `{**attempts, **kwargs}`: a caller naming an attempt field replaces the value built
        // for it and leaves it where it was, which is what re-inserting over a key does.
        for (name, value) in inputs.fields() {
            asking.set(name, value.clone());
        }
        let names: Vec<String> = asking.fields().map(|(name, _)| name.to_owned()).collect();
        Ok(asking.with_inputs(names))
    }

    /// One attempt as the model reads it: what the student was trying, and what it predicted.
    fn attempt(&self, completion: &Example) -> Result<String> {
        // A ChainOfThought completion names the field `reasoning`; only this fallback lets one
        // be compared at all. A value that is not a string fails, matching upstream, where the
        // reasoning goes straight to `str.strip` while the prediction goes through `str` first.
        let rationale = completion
            .get("rationale")
            .or_else(|| completion.get("reasoning"))
            .and_then(Value::as_str)
            .ok_or_else(|| {
                anyhow!("a compared completion needs a string rationale or reasoning field")
            })?;
        let answer = completion
            .get(&self.last_key)
            .map(format_value)
            .ok_or_else(|| anyhow!("a compared completion has no {} field", self.last_key))?;
        Ok(format!(
            "«I'm trying to {} I'm not sure but my prediction is {}»",
            first_line(rationale),
            first_line(&answer)
        ))
    }
}

fn attempt_field(index: usize) -> String {
    format!("reasoning_attempt_{index}")
}

/// Python `text.strip().split("\n")[0].strip()`: the opening line of a value, with the strip on
/// both sides of the cut.
///
/// The second strip is not the first repeated. The first decides which line is the opening one —
/// leading blank lines belong to no line — and the second cleans the line it settled on.
fn first_line(text: &str) -> &str {
    strip(strip(text).split('\n').next().unwrap_or_default())
}

/// Python `str.strip()`, whose whitespace is Unicode's plus the four separator controls.
///
/// `\x1c`–`\x1f` are whitespace to Python and are not in Unicode's `White_Space`, so
/// `str::trim` leaves them where Python takes them away. Nothing else in the two sets differs.
fn strip(text: &str) -> &str {
    text.trim_matches(|c: char| c.is_whitespace() || ('\u{1c}'..='\u{1f}').contains(&c))
}

/// A comparison is one predictor, so an optimizer rewriting demos and instructions reaches the
/// signature the attempts were added to.
///
/// [`Module::forward`] asks that predictor with the inputs it is handed, which is what upstream's
/// own `forward` does once it has built the attempt fields — it does not build them, because the
/// completions have nowhere to arrive through a trait shared with every other module.
/// [`MultiChainComparison::compare`] is the call that builds them.
impl Module for MultiChainComparison {
    fn forward<'a>(
        &'a self,
        inputs: Example,
    ) -> std::pin::Pin<Box<dyn Future<Output = Result<Prediction>> + Send + 'a>> {
        self.predict.forward(inputs)
    }

    fn forward_traced<'a>(
        &'a self,
        inputs: Example,
        trace: &'a mut Vec<TraceStep>,
    ) -> std::pin::Pin<Box<dyn Future<Output = Result<Prediction>> + Send + 'a>> {
        self.predict.forward_traced(inputs, trace)
    }

    fn named_predictors(&mut self) -> Vec<NamedPredictor<'_>> {
        self.predict.named_predictors()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::adapter::{Adapter, ChatAdapter};
    use serde_json::json;

    /// What dspy builds and sends, recorded by running it. Regenerate with
    /// `scripts/generate_mcc_fixture.py`.
    fn golden() -> Value {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/conformance/predict/mcc.json");
        let text = std::fs::read_to_string(&path).expect("the mcc golden is committed");
        serde_json::from_str(&text).expect("the golden parses")
    }

    fn cases() -> Vec<Value> {
        let cases = golden()["cases"].as_array().expect("cases").clone();
        assert!(!cases.is_empty(), "the golden records no cases");
        cases
    }

    /// The signature as it stood before the module edited it, rebuilt from what dspy reported.
    fn base(case: &Value) -> Signature {
        let described = |field: &Value| {
            (
                field["name"].as_str().expect("a name").to_owned(),
                field["rendered_desc"].as_str().expect("a desc").to_owned(),
            )
        };
        let fields = |side: &str| -> Vec<(String, String)> {
            case["base"][side]
                .as_array()
                .expect("fields")
                .iter()
                .map(described)
                .collect()
        };
        Signature {
            instructions: case["base"]["instructions"]
                .as_str()
                .expect("instructions")
                .to_owned(),
            inputs: fields("inputs")
                .into_iter()
                .map(|(name, desc)| InField {
                    name,
                    desc,
                    ..Default::default()
                })
                .collect(),
            outputs: fields("outputs")
                .into_iter()
                .map(|(name, desc)| OutField {
                    name,
                    desc,
                    ..Default::default()
                })
                .collect(),
        }
    }

    fn module(case: &Value) -> MultiChainComparison {
        let attempts = case["m"].as_u64().expect("an M") as usize;
        MultiChainComparison::with_attempts(base(case), attempts).expect("the module builds")
    }

    fn example(fields: &Value) -> Example {
        Example::new(
            fields
                .as_object()
                .expect("an object")
                .iter()
                .map(|(name, value)| (name.as_str(), value.clone())),
        )
    }

    fn completions(case: &Value) -> Vec<Example> {
        case["completions"]
            .as_array()
            .expect("completions")
            .iter()
            .map(example)
            .collect()
    }

    fn asking(case: &Value) -> Example {
        module(case)
            .asking(&completions(case), example(&case["caller_inputs"]))
            .expect("the inputs build")
    }

    #[test]
    fn builds_the_signature_dspy_builds() {
        for case in cases() {
            let built = module(&case).predict.signature.clone();
            let expected = &case["built"];
            assert_eq!(
                built.instructions,
                expected["instructions"].as_str().expect("instructions"),
                "instructions of {}",
                case["name"]
            );

            let named = |side: &str, names: Vec<(&str, &str)>| {
                let want: Vec<(&str, &str)> = expected[side]
                    .as_array()
                    .expect("fields")
                    .iter()
                    .map(|field| {
                        (
                            field["name"].as_str().expect("a name"),
                            field["rendered_desc"].as_str().expect("a desc"),
                        )
                    })
                    .collect();
                assert_eq!(names, want, "{side} of {}", case["name"]);
            };
            named(
                "inputs",
                built
                    .inputs
                    .iter()
                    .map(|f| (f.name.as_str(), f.desc.as_str()))
                    .collect(),
            );
            named(
                "outputs",
                built
                    .outputs
                    .iter()
                    .map(|f| (f.name.as_str(), f.desc.as_str()))
                    .collect(),
            );
        }
    }

    /// The whole message a model would receive, which is the only claim worth making: a field
    /// list that matches while the prompt does not is the failure mode this crate keeps hitting.
    ///
    /// The values are put in signature order before rendering, matching `tests/conformance.rs`.
    /// dspy's `format_user_message_content` walks `signature.input_fields` and skips what it was
    /// not given, so the order a caller passes is unobservable there; `chat_user` walks what it
    /// was given instead, and this module is the first caller whose natural order — every attempt
    /// before the request they answer — is not the signature's. That divergence belongs to the
    /// adapter, so it is not worked around here and this test does not claim it.
    #[test]
    fn renders_the_prompt_dspy_renders() {
        for case in cases() {
            let module = module(&case);
            let inputs = asking(&case);
            let values: Vec<(&str, Value)> = module
                .predict
                .signature
                .inputs
                .iter()
                .filter_map(|field| Some((field.name.as_str(), inputs.get(&field.name)?.clone())))
                .collect();
            let (system, turns) = ChatAdapter::default()
                .format(&module.predict.signature, &[], &values)
                .expect("the prompt renders");

            assert_eq!(
                system,
                case["system"].as_str().expect("a system message"),
                "system message of {}",
                case["name"]
            );
            assert_eq!(turns.len(), 1, "one user turn for {}", case["name"]);
            assert_eq!(
                turns[0].content.text().expect("text"),
                case["user"].as_str().expect("a user message"),
                "user message of {}",
                case["name"]
            );
        }
    }

    /// Every attempt string, in the order and under the names dspy hands to `Predict` — which is
    /// where a caller's own value for an attempt field is seen to have replaced one.
    #[test]
    fn formats_the_attempts_dspy_formats() {
        for case in cases() {
            let sent: Vec<(String, Value)> = asking(&case)
                .fields()
                .map(|(name, value)| (name.to_owned(), value.clone()))
                .collect();
            let want: Vec<(String, Value)> = case["sent"]
                .as_array()
                .expect("sent")
                .iter()
                .map(|pair| {
                    (
                        pair[0].as_str().expect("a name").to_owned(),
                        pair[1].clone(),
                    )
                })
                .collect();
            assert_eq!(sent, want, "inputs sent for {}", case["name"]);
        }
    }

    #[test]
    fn a_miscounted_set_of_attempts_reads_like_dspys_assertion() {
        for case in golden()["count_mismatch"].as_array().expect("cases") {
            let attempts = case["m"].as_u64().expect("an M") as usize;
            let given = case["given"].as_u64().expect("a count") as usize;
            let module = MultiChainComparison::with_attempts(base(&cases()[0]), attempts)
                .expect("the module builds");
            let completions = vec![example(&json!({ "rationale": "r", "answer": "a" })); given];

            let error = module
                .asking(&completions, Example::default())
                .expect_err("a miscount is refused")
                .to_string();
            assert_eq!(error, case["message"].as_str().expect("a message"));
        }
    }

    /// dspy fails here too, on the unpacking that looks for a last output field. Only the
    /// failure is held to: its message is CPython's, not a literal dspy wrote.
    #[test]
    fn a_signature_with_no_outputs_has_no_answer_to_compare() {
        let signature = Signature {
            instructions: "Nothing to say.".into(),
            inputs: vec![InField {
                name: "question".into(),
                ..Default::default()
            }],
            outputs: Vec::new(),
        };
        assert!(
            MultiChainComparison::from_signature(signature).is_err(),
            "dspy refuses this with: {}",
            golden()["no_output_fields"]
        );
    }

    #[test]
    fn strips_the_whitespace_python_strips() {
        for case in golden()["python_strip"].as_array().expect("cases") {
            let text = case["text"].as_str().expect("a text");
            let expected = case["stripped"].as_str().expect("a result");
            assert_eq!(strip(text), expected, "strip({text:?})");
        }
    }

    #[test]
    fn a_completion_without_usable_reasoning_is_refused() {
        let module =
            MultiChainComparison::with_attempts(base(&cases()[0]), 1).expect("the module builds");
        for completion in [
            json!({ "answer": "blue" }),
            json!({ "rationale": 7, "answer": "blue" }),
        ] {
            assert!(
                module.attempt(&example(&completion)).is_err(),
                "upstream raises AttributeError for {completion}"
            );
        }
        assert!(
            module
                .attempt(&example(&json!({ "rationale": "r" })))
                .is_err(),
            "upstream raises KeyError when the answer field is absent"
        );
    }
}
