//! dspy `infer_prefix` (`signatures/signature.py`): a field's name becomes the label an adapter
//! prints in front of it.
//!
//! Upstream reaches the answer through four regular expressions applied in order, then title
//! cases what they produced. Each is reproduced as its own left-to-right pass because they
//! disagree about where a boundary is, and the order in which they disagree is what decides the
//! result: the first splits a capital that begins a word, the second a capital that follows a
//! lowercase, and the last two split letters from digits.
//!
//! Held to `tests/conformance/signature/signature.json`, generated by running dspy.

use unicode_general_category::{GeneralCategory, get_general_category};

pub fn infer_prefix(name: &str) -> String {
    let chars: Vec<char> = name.chars().collect();
    let split = split_before_a_capitalised_word(&chars);
    let split = split_between(&split, |left, right| {
        (left.is_ascii_lowercase() || left.is_ascii_digit()) && right.is_ascii_uppercase()
    });
    let split = split_between(&split, |left, right| {
        left.is_ascii_alphabetic() && is_decimal(right)
    });
    let split = split_between(&split, |left, right| {
        is_decimal(left) && right.is_ascii_alphabetic()
    });
    title_case(&split)
}

/// Python's `\d`, which is decimal digits and nothing else.
///
/// Narrower than `char::is_numeric`, which also takes letter-numerics like `Ⅻ` and
/// other-numerics like `½`. Upstream splits around neither, and its character classes for
/// letters are ASCII besides, so a name may split around a digit it cannot split around a
/// capital: `text٢number` becomes three words where `ПриветМир` stays one.
fn is_decimal(character: char) -> bool {
    get_general_category(character) == GeneralCategory::DecimalNumber
}

/// `(.)([A-Z][a-z]+)`: a capital that opens a lowercase word, wherever one precedes it.
///
/// The leading `(.)` is part of the match, so the run it consumes is not offered to the next
/// one. That is why `camelCaseText` leaves this pass as `camel_CaseText` rather than already
/// split at both boundaries, and why the pass below exists to find the second.
fn split_before_a_capitalised_word(chars: &[char]) -> Vec<char> {
    let mut split = Vec::with_capacity(chars.len());
    let mut at = 0;
    while at < chars.len() {
        let opens_a_word = chars.get(at + 1).is_some_and(char::is_ascii_uppercase);
        let run = lowercase_run(chars, at + 2);
        if opens_a_word && run > 0 {
            split.push(chars[at]);
            split.push('_');
            split.extend(&chars[at + 1..at + 2 + run]);
            at += 2 + run;
        } else {
            split.push(chars[at]);
            at += 1;
        }
    }
    split
}

fn lowercase_run(chars: &[char], from: usize) -> usize {
    chars
        .get(from..)
        .map(|rest| rest.iter().take_while(|c| c.is_ascii_lowercase()).count())
        .unwrap_or(0)
}

/// One two-character expression: where `boundary` holds, an underscore goes between.
fn split_between(chars: &[char], boundary: impl Fn(char, char) -> bool) -> Vec<char> {
    let mut split = Vec::with_capacity(chars.len());
    let mut at = 0;
    while at < chars.len() {
        match chars.get(at + 1) {
            // Both characters are consumed, so a run of boundaries splits every other gap —
            // which is what a non-overlapping substitution does.
            Some(&right) if boundary(chars[at], right) => {
                split.extend([chars[at], '_', right]);
                at += 2;
            }
            _ => {
                split.push(chars[at]);
                at += 1;
            }
        }
    }
    split
}

/// Title case each underscore-separated word, leaving an acronym as it stands.
fn title_case(chars: &[char]) -> String {
    chars
        .split(|&c| c == '_')
        .map(|word| {
            if is_upper(word) {
                return word.iter().collect();
            }
            capitalize(word)
        })
        .collect::<Vec<String>>()
        .join(" ")
}

/// Python `str.isupper`: every cased character is uppercase, and there is at least one.
fn is_upper(word: &[char]) -> bool {
    word.iter().any(|c| c.is_uppercase()) && !word.iter().any(|c| c.is_lowercase())
}

/// Python `str.capitalize`: the first character upper, every other one lower.
fn capitalize(word: &[char]) -> String {
    let mut characters = word.iter();
    let Some(first) = characters.next() else {
        return String::new();
    };
    first
        .to_uppercase()
        .chain(characters.flat_map(|c| c.to_lowercase()))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    use serde_json::Value;

    /// What dspy answers, recorded by running it. Regenerate with
    /// `scripts/generate_signature_fixture.py`.
    fn golden() -> Value {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/conformance/signature/signature.json");
        let text = std::fs::read_to_string(&path).expect("the signature golden is committed");
        serde_json::from_str(&text).expect("the golden parses")
    }

    #[test]
    fn infers_the_prefix_dspy_infers() {
        let cases = golden()["infer_prefix"].as_array().expect("cases").clone();
        assert!(!cases.is_empty(), "the golden records no names");
        for case in cases {
            let name = case["name"].as_str().expect("a name");
            let expected = case["prefix"].as_str().expect("a prefix");
            assert_eq!(infer_prefix(name), expected, "infer_prefix({name:?})");
        }
    }
}
