//! dspy `predict/flex/`: a module whose implementation is optimizable *code* rather than a prompt.
//!
//! Every other module here is a fixed shape an optimizer tunes the instructions of. A [`Flex`] is
//! the other thing: its state is a **string of Python source** defining a module, and GEPA rewrites
//! that source into decomposed predictors plus plain Python. The source never runs in this process
//! — it runs in a sandboxed Python interpreter, and the predictors it builds bridge back out to the
//! host, which makes the real model calls.
//!
//! That the guest is Python in both ports is what makes this reproducible: the shim the sandbox
//! runs is upstream's own file, byte for byte, and the two strings the guest sees — the signature
//! rendered back to `"in: T -> out: T2"` and the baseline module built around it — are compared
//! against `tests/conformance/predict/flex.json`, generated by running dspy.

mod bridge;
mod built;
mod rendering;

pub use rendering::class_name_of;
pub mod proposal;

use std::sync::Arc;

use anyhow::{Result, bail};

use crate::example::{Example, Prediction};
use crate::interpreter::{DenoInterpreter, InterpreterFactory, factory};
use crate::module::{FlexState, Module, NamedFlex, ProgramState, SubmoduleState};
use crate::react::Tool;
use crate::signature::Signature;

/// The sandbox side of the bridge, as upstream ships it.
///
/// Vendored rather than rewritten because the guest is Python here exactly as it is upstream: this
/// source defines the stand-in `dspy` module the optimizer-authored code imports, and any drift
/// from it is drift in what that code is allowed to say. `a_vendored_shim_matches_upstreams` holds
/// it to the pinned file byte for byte.
pub const SANDBOX_SHIM: &str = include_str!("flex/_sandbox_shim.py");

/// dspy's class name for a signature built from a string, which the generated module is named after.
///
/// `dspy.Signature("question -> answer")` builds a class called `StringSignature`, so every module
/// generated from a string signature is `StringSignatureModule`. A Rust `Signature` carries no
/// class name, so this is the default and [`Flex::named`] is how a declared one says otherwise.
const STRING_SIGNATURE: &str = "StringSignature";

/// dspy `Flex`: a module whose implementation is code an optimizer rewrites.
pub struct Flex {
    signature: Signature,
    name: String,
    tools: Vec<Arc<dyn Tool>>,
    module_src: String,
    /// dspy's `interpreter_factory`: one sandbox per forward, shut down after — the same seam
    /// `ProgramOfThought` takes, so a caller who cannot run Deno supplies their own.
    interpreter_factory: InterpreterFactory,
    /// dspy's `max_predictor_calls`: how many predictor calls one forward may make, `None` for no
    /// cap. See [`max_predictor_calls`](Self::max_predictor_calls).
    max_predictor_calls: Option<usize>,
}

/// dspy's `max_predictor_calls=100`: the default budget for one forward.
const DEFAULT_PREDICTOR_CALLS: usize = 100;

impl Flex {
    /// A `Flex` over this signature, holding the baseline source until an optimizer replaces it.
    pub fn new(signature: Signature) -> Self {
        let mut flex = Self {
            signature,
            name: STRING_SIGNATURE.to_owned(),
            tools: Vec::new(),
            module_src: String::new(),
            interpreter_factory: factory(DenoInterpreter::new),
            max_predictor_calls: Some(DEFAULT_PREDICTOR_CALLS),
        };
        flex.module_src = flex.baseline_src();
        flex
    }

    /// dspy's `interpreter_factory`: what builds the sandbox each forward runs in.
    ///
    /// The optimizer-authored source never runs in this process, so this decides the Python and
    /// standard-library subset it is allowed to use.
    pub fn interpreter_factory(mut self, interpreter_factory: InterpreterFactory) -> Self {
        self.interpreter_factory = interpreter_factory;
        self
    }

    /// dspy's `max_predictor_calls`: how many predictor calls one forward may make.
    ///
    /// The source a `Flex` runs is written by a model and runs unattended, so a loop around a
    /// predictor is one bad proposal away from spending a budget. `None` removes the cap, which is
    /// upstream's own escape hatch and means what it says.
    pub fn max_predictor_calls(mut self, max_predictor_calls: Option<usize>) -> Self {
        self.max_predictor_calls = max_predictor_calls;
        self
    }

    /// The signature's own name, which the generated class is built from — dspy's `__name__`.
    pub fn named(mut self, name: impl Into<String>) -> Self {
        self.name = name.into();
        self.module_src = self.baseline_src();
        self
    }

    /// The tools the generated code may call by name, which also makes the baseline an `RLM`.
    ///
    /// Upstream refuses a name that is not a Python identifier or that belongs to the sandbox's own
    /// namespace, because the generated code references it by name — the same two refusals here.
    pub fn with_tools(mut self, tools: Vec<Arc<dyn Tool>>) -> Result<Self> {
        for tool in &tools {
            let name = tool.name();
            if !rendering::is_identifier(name) {
                bail!(
                    "Tool {name:?} needs a name that is a valid Python identifier — it is \
                     referenced by name in the generated code"
                );
            }
            if name == "dspy" || name.starts_with("_dspy") || name.starts_with("__dspy") {
                bail!(
                    "Tool name {name:?} is reserved: 'dspy' and names starting with '_dspy' \
                     belong to the dspy.Flex sandbox"
                );
            }
        }
        self.tools = tools;
        self.module_src = self.baseline_src();
        Ok(self)
    }

    /// The source the sandbox runs — dspy's `module_src`, and a `Flex`'s whole optimizable state.
    pub fn module_src(&self) -> &str {
        &self.module_src
    }

    /// Replace it, which is what an optimizer does instead of rewriting instructions.
    pub fn bind(&mut self, module_src: impl Into<String>) -> Result<()> {
        let module_src = module_src.into();
        rendering::class_name_of(&module_src)?;
        self.module_src = module_src;
        Ok(())
    }

    pub fn signature(&self) -> &Signature {
        &self.signature
    }
}

impl Module for Flex {
    /// dspy's `enumerate_flex_submodules` reaching a leaf: a `Flex` is the one it was looking for.
    ///
    /// Named `self` as every bare module here names itself; a `Flex` inside a program is renamed by
    /// the parent that recurses into it, which is what `named_predictors` does one method over.
    fn named_flexes(&mut self) -> Vec<NamedFlex<'_>> {
        vec![NamedFlex {
            name: "self".to_owned(),
            flex: self,
        }]
    }

    /// dspy's `Flex.dump_state`: the source, and the model it was pinned to.
    ///
    /// A `Flex`'s update unit is its `module_src`, not a signature and some demos — which is why
    /// the state map holds a [`SubmoduleState`] rather than a predictor state. Keyed `self` as every
    /// bare module here is; a `Flex` inside a program is keyed by its attribute, as upstream keys it.
    fn dump_state(&mut self) -> ProgramState {
        ProgramState::new(
            [(
                "self".to_owned(),
                SubmoduleState::Flex(FlexState {
                    module_src: Some(self.module_src.clone()),
                    lm: None,
                }),
            )]
            .into(),
        )
    }

    /// dspy's `Flex.load_state`: bind the saved source.
    ///
    /// Upstream keeps the current source when the state carries none, and so does this — a state
    /// written before anything optimized it has nothing to say about the module's shape.
    fn load_state_with(
        &mut self,
        state: &ProgramState,
        _trust: crate::module::Trust,
    ) -> Result<()> {
        let Some(SubmoduleState::Flex(saved)) = state.state("self") else {
            bail!("the saved state has no dspy.Flex entry for \"self\"");
        };
        if let Some(module_src) = &saved.module_src {
            self.bind(module_src.clone())?;
        }
        Ok(())
    }

    /// dspy's `Flex.forward`: run the bound source in a fresh sandbox and read its prediction back.
    ///
    /// The predictors the generated code builds are this crate's and run here, which is what makes
    /// the model calls real. That crossing costs a thread: `CodeInterpreter::execute` and
    /// [`Tool::call`] are synchronous the whole way down and this is not, so the interpreter runs
    /// on its own while the predictors it asks for are built and called here.
    fn forward<'a>(
        &'a self,
        inputs: Example,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<Prediction>> + Send + 'a>> {
        Box::pin(async move {
            let class_name = class_name_of(&self.module_src)?;
            let answered = bridge::run(
                self.interpreter_factory.clone(),
                SANDBOX_SHIM,
                &self.module_src,
                &class_name,
                self.tools.clone(),
                inputs
                    .fields()
                    .map(|(name, value)| (name.to_owned(), value.clone()))
                    .collect(),
                self.max_predictor_calls,
            )
            .await?;
            bridge::prediction_of(&answered, &self.signature)
        })
    }
}
