//! dspy `predict/flex/`: a module whose implementation is optimizable *code* rather than a prompt.
//!
//! Every other module here is a fixed shape an optimizer tunes the instructions of. A [`Flex`] is
//! the other thing: its state is a **string of Python source** defining a module, and GEPA rewrites
//! that source into decomposed predictors plus plain Python. The source never runs in this process
//! — it runs in a sandboxed Python interpreter, and the predictors it builds bridge back out to the
//! host, which makes the real model calls.
//!
//! That the guest is Python in both ports is what makes this reproducible: the shim the sandbox
//! runs is upstream's own file, byte for byte, and the two strings the guest sees — the signature
//! rendered back to `"in: T -> out: T2"` and the baseline module built around it — are compared
//! against `tests/conformance/predict/flex.json`, generated by running dspy.

mod bridge;

use std::sync::Arc;

use anyhow::{Result, bail};

use crate::example::{Example, Prediction};
use crate::interpreter::{DenoInterpreter, InterpreterFactory, factory};
use crate::module::Module;
use crate::react::Tool;
use crate::signature::Signature;

/// The sandbox side of the bridge, as upstream ships it.
///
/// Vendored rather than rewritten because the guest is Python here exactly as it is upstream: this
/// source defines the stand-in `dspy` module the optimizer-authored code imports, and any drift
/// from it is drift in what that code is allowed to say. `a_vendored_shim_matches_upstreams` holds
/// it to the pinned file byte for byte.
pub const SANDBOX_SHIM: &str = include_str!("flex/_sandbox_shim.py");

/// dspy's class name for a signature built from a string, which the generated module is named after.
///
/// `dspy.Signature("question -> answer")` builds a class called `StringSignature`, so every module
/// generated from a string signature is `StringSignatureModule`. A Rust `Signature` carries no
/// class name, so this is the default and [`Flex::named`] is how a declared one says otherwise.
const STRING_SIGNATURE: &str = "StringSignature";

/// dspy `Flex`: a module whose implementation is code an optimizer rewrites.
pub struct Flex {
    signature: Signature,
    name: String,
    tools: Vec<Arc<dyn Tool>>,
    module_src: String,
    /// dspy's `interpreter_factory`: one sandbox per forward, shut down after — the same seam
    /// `ProgramOfThought` takes, so a caller who cannot run Deno supplies their own.
    interpreter_factory: InterpreterFactory,
}

impl Flex {
    /// A `Flex` over this signature, holding the baseline source until an optimizer replaces it.
    pub fn new(signature: Signature) -> Self {
        let mut flex = Self {
            signature,
            name: STRING_SIGNATURE.to_owned(),
            tools: Vec::new(),
            module_src: String::new(),
            interpreter_factory: factory(DenoInterpreter::new),
        };
        flex.module_src = flex.baseline_src();
        flex
    }

    /// dspy's `interpreter_factory`: what builds the sandbox each forward runs in.
    ///
    /// The optimizer-authored source never runs in this process, so this decides the Python and
    /// standard-library subset it is allowed to use.
    pub fn interpreter_factory(mut self, interpreter_factory: InterpreterFactory) -> Self {
        self.interpreter_factory = interpreter_factory;
        self
    }

    /// The signature's own name, which the generated class is built from — dspy's `__name__`.
    pub fn named(mut self, name: impl Into<String>) -> Self {
        self.name = name.into();
        self.module_src = self.baseline_src();
        self
    }

    /// The tools the generated code may call by name, which also makes the baseline an `RLM`.
    ///
    /// Upstream refuses a name that is not a Python identifier or that belongs to the sandbox's own
    /// namespace, because the generated code references it by name — the same two refusals here.
    pub fn with_tools(mut self, tools: Vec<Arc<dyn Tool>>) -> Result<Self> {
        for tool in &tools {
            let name = tool.name();
            if !is_identifier(name) {
                bail!(
                    "Tool {name:?} needs a name that is a valid Python identifier — it is \
                     referenced by name in the generated code"
                );
            }
            if name == "dspy" || name.starts_with("_dspy") || name.starts_with("__dspy") {
                bail!(
                    "Tool name {name:?} is reserved: 'dspy' and names starting with '_dspy' \
                     belong to the dspy.Flex sandbox"
                );
            }
        }
        self.tools = tools;
        self.module_src = self.baseline_src();
        Ok(self)
    }

    /// The source the sandbox runs — dspy's `module_src`, and a `Flex`'s whole optimizable state.
    pub fn module_src(&self) -> &str {
        &self.module_src
    }

    /// Replace it, which is what an optimizer does instead of rewriting instructions.
    pub fn bind(&mut self, module_src: impl Into<String>) -> Result<()> {
        let module_src = module_src.into();
        class_name_of(&module_src)?;
        self.module_src = module_src;
        Ok(())
    }

    pub fn signature(&self) -> &Signature {
        &self.signature
    }

    /// dspy's `render_signature_string`: the signature back as `"in: T, in2 -> out: T2"`.
    ///
    /// Every field carries its annotation, so a signature parsed from bare names renders with the
    /// `str` the parse gave them — `"question -> answer"` comes back as `"question: str -> answer: str"`.
    pub fn signature_string(&self) -> String {
        let inputs: Vec<String> = self
            .signature
            .inputs
            .iter()
            .map(|field| format!("{}: {}", field.name, field.annotation()))
            .collect();
        let outputs: Vec<String> = self
            .signature
            .outputs
            .iter()
            .map(|field| format!("{}: {}", field.name, field.annotation()))
            .collect();
        format!("{} -> {}", inputs.join(", "), outputs.join(", "))
    }

    /// dspy's `_class_name`: the generated class, named after the signature.
    pub fn class_name(&self) -> String {
        let base = match is_identifier(&self.name) {
            true => self.name.as_str(),
            false => "Flex",
        };
        format!("{base}Module")
    }

    /// dspy's `_baseline_src`: one predictor over the whole signature, wrapped in a module.
    ///
    /// An `RLM` when tools were given, so the baseline can call them, and a `Predict` otherwise.
    /// The signature always arrives as `dspy.Signature(string, instructions)` rather than as a bare
    /// string, because dspy writes default instructions for a signature nobody wrote any for — the
    /// branch upstream keeps for empty instructions is unreachable from a parsed signature.
    fn baseline_src(&self) -> String {
        let returns: Vec<String> = self
            .signature
            .outputs
            .iter()
            .map(|field| format!("{}=result.{}", field.name, field.name))
            .collect();
        let signature = python_repr(&self.signature_string());
        let sig_arg = match self.signature.instructions.trim().is_empty() {
            true => signature,
            false => format!(
                "dspy.Signature({signature}, {})",
                python_repr(self.signature.instructions.trim())
            ),
        };
        let (attr, ctor) = match self.tools.is_empty() {
            true => ("predict", format!("dspy.Predict({sig_arg})")),
            false => {
                let names: Vec<&str> = self.tools.iter().map(|tool| tool.name()).collect();
                (
                    "rlm",
                    format!("dspy.RLM({sig_arg}, tools=[{}])", names.join(", ")),
                )
            }
        };
        format!(
            "class {}(dspy.Module):\n\
             \x20   def __init__(self):\n\
             \x20       super().__init__()\n\
             \x20       self.{attr} = {ctor}\n\
             \n\
             \x20   def forward(self, **inputs):\n\
             \x20       result = self.{attr}(**inputs)\n\
             \x20       return dspy.Prediction({})",
            self.class_name(),
            returns.join(", ")
        )
    }
}

/// dspy's `parse_module_class_name`: the generated module's class, read out of the source.
///
/// Upstream parses with `ast` and prefers the first class defining `forward`, falling back to the
/// first class at all. Reproduced as a scan because the shape is fixed — a module-level `class` line
/// and a `def forward` indented under it — and a Python parser is not something this crate carries.
pub fn class_name_of(module_src: &str) -> Result<String> {
    let mut classes: Vec<(String, bool)> = Vec::new();
    for line in module_src.lines() {
        if let Some(rest) = line.strip_prefix("class ") {
            let name: String = rest
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                classes.push((name, false));
            }
        } else if line.trim_start().starts_with("def forward(")
            && line.starts_with(char::is_whitespace)
        {
            if let Some(last) = classes.last_mut() {
                last.1 = true;
            }
        }
    }
    let chosen = classes
        .iter()
        .find(|(_, has_forward)| *has_forward)
        .or_else(|| classes.first());
    match chosen {
        Some((name, _)) => Ok(name.clone()),
        None => bail!("module_src must define a dspy.Module subclass with a `forward` method"),
    }
}

/// Python's `str.isidentifier`, over the ASCII a generated name can use.
fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    chars
        .next()
        .is_some_and(|first| first.is_alphabetic() || first == '_')
        && chars.all(|c| c.is_alphanumeric() || c == '_')
}

/// Python's `repr` of a string, which is what the generated source embeds.
///
/// Single quotes unless the value holds one and no double quote — the rule `quoted_member` follows
/// for a literal annotation, and Python's own.
fn python_repr(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\");
    match (escaped.contains('\''), escaped.contains('"')) {
        (true, false) => format!("\"{escaped}\""),
        (true, true) => format!("'{}'", escaped.replace('\'', "\\'")),
        _ => format!("'{escaped}'"),
    }
}

impl Module for Flex {
    /// dspy's `Flex.forward`: run the bound source in a fresh sandbox and read its prediction back.
    ///
    /// The predictors the generated code builds are this crate's and run here, which is what makes
    /// the model calls real. That crossing costs a thread: `CodeInterpreter::execute` and
    /// [`Tool::call`] are synchronous the whole way down and this is not, so the interpreter runs
    /// on its own while the predictors it asks for are built and called here.
    fn forward<'a>(
        &'a self,
        inputs: Example,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<Prediction>> + Send + 'a>> {
        Box::pin(async move {
            let interpreter = (self.interpreter_factory)()?;
            let class_name = class_name_of(&self.module_src)?;
            let answered = bridge::run(
                interpreter,
                SANDBOX_SHIM,
                &self.module_src,
                &class_name,
                self.tools.clone(),
                inputs
                    .fields()
                    .map(|(name, value)| (name.to_owned(), value.clone()))
                    .collect(),
            )
            .await?;
            bridge::prediction_of(&answered, &self.signature)
        })
    }
}
