//! What a model can be asked for natively, and how a model reference is looked up.
//!
//! dspy answers `supports_function_calling` and its two siblings by handing the model name to
//! litellm, which reads them out of a bundled registry. There is no rule behind the answers to
//! reimplement — `claude-3-5-sonnet-20241022` cannot take a tool list while `claude-opus-4-1`
//! can — so the registry travels with this crate instead, generated by
//! `scripts/generate_lm_capabilities_fixture.py`.
//!
//! **Ollama is not in the registry's gift**, and litellm does not pretend otherwise: what an
//! ollama server can do is whatever has been pulled onto it, so litellm asks the server. So does
//! this, in `ollama/capabilities.rs`, which is why
//! [`ChatModel::capabilities`](crate::lm::ChatModel::capabilities) is asynchronous. The registry
//! still answers first, for the ollama models litellm does list; only an unlisted one is a
//! question for the server.

use std::collections::HashMap;
use std::sync::OnceLock;

/// What a model can be asked to do natively, rather than through the prompt.
///
/// dspy asks a model three separate questions, each a `BaseLM` property defaulting to `False`.
/// They travel together here because they are one question about one model, and because a trait
/// carrying three defaulted predicates makes an implementor answer three times to say nothing.
///
/// Everything is off by default, as upstream has it: a model this crate knows nothing about
/// cannot be assumed to honour a feature, and asking for one it lacks is a failed request rather
/// than a degraded one.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Capabilities {
    /// dspy `supports_function_calling`: the provider will take a tool list and answer with
    /// calls, so an adapter need not ask for them as a rendered field.
    pub function_calling: bool,
    /// dspy `supports_reasoning`: the model exposes extended thinking as its own channel.
    pub reasoning: bool,
    /// dspy `supports_response_schema`: the provider will constrain the reply to a JSON schema,
    /// rather than being merely told about one.
    pub response_schema: bool,
}

impl Capabilities {
    /// What the registry credits `model` with, by the reference a caller wrote —
    /// `openai/gpt-4o`, `ollama/llama3.2`, `openrouter/openai/gpt-4o`.
    ///
    /// litellm answers for a model under more than one spelling: OpenAI's models are keyed bare
    /// (`gpt-4o`), while the routed providers keep their prefix (`openrouter/openai/gpt-4o`,
    /// `ollama/llama3.2`). Trying the whole reference and then the part after the first slash
    /// covers both, and `tests/lm_capabilities.rs` holds that to litellm's own answers rather
    /// than to this description of them.
    pub fn of(model: &str) -> Self {
        Self::listed(model).unwrap_or_default()
    }

    /// What the registry says, or `None` where it does not list the model at all.
    ///
    /// The distinction only matters for ollama, where litellm treats an unlisted model as a
    /// question for the server rather than as an answer — so an ollama row crediting nothing is
    /// kept in the table, to be told apart from no row.
    pub fn listed(model: &str) -> Option<Self> {
        registry()
            .get(model)
            .or_else(|| registry().get(model.split_once('/')?.1))
            .copied()
    }
}

/// The vendored registry, read once.
fn registry() -> &'static HashMap<String, Capabilities> {
    static REGISTRY: OnceLock<HashMap<String, Capabilities>> = OnceLock::new();
    REGISTRY.get_or_init(|| {
        let table: Table = serde_json::from_str(include_str!("capabilities.json"))
            .expect("the vendored capability registry is valid json");
        table
            .models
            .into_iter()
            .map(|(model, [function_calling, reasoning, response_schema])| {
                (model, Capabilities { function_calling, reasoning, response_schema })
            })
            .collect()
    })
}

/// The generated file's shape: each model against its flags, in the order [`Capabilities`]
/// declares them.
#[derive(serde::Deserialize)]
struct Table {
    models: HashMap<String, [bool; 3]>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_unknown_model_is_credited_with_nothing() {
        // Upstream's default too: what is not known is not assumed.
        assert_eq!(Capabilities::of("openai/nothing-like-this"), Capabilities::default());
        assert_eq!(Capabilities::of("no-slash-at-all"), Capabilities::default());
    }

    #[test]
    fn the_registry_loads_and_is_not_trivially_small() {
        // A registry that failed to parse into an empty map would make every lookup answer
        // "no capabilities", which is the same reading as a model the file does not list.
        assert!(registry().len() > 1000, "only {} models", registry().len());
    }
}
