#!/usr/bin/env bash
# Build a crate that depends on `dsrust` and nothing else.
#
# The workspace cannot see what a caller sees. `extern crate self as dsrust` makes `::dsrust`
# resolve inside this repo, every test here already has serde and schemars, and so a derive that
# expands to `::serde::Serialize` compiles perfectly in every test we run and fails for everyone
# else. That is exactly what happened: a real project reported that `#[derive(Signature)]` forced
# it to add serde and serde_json of its own, and no gate here could have caught it.
#
# So the gate is a crate outside the workspace, with one dependency, exercising the surface a
# caller reaches first: derive a signature, build a module from it, read a field back.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$ROOT/target/external-consumer"

mkdir -p "$WORK/src"
cat > "$WORK/Cargo.toml" <<EOF
# Generated by scripts/check_external_consumer.sh. The point is the dependency list: one entry.
[package]
name = "external-consumer"
version = "0.0.0"
edition = "2024"

[dependencies]
dsrust = { path = "$ROOT" }

# Its own workspace, so the repo's does not lend it dependencies it never declared.
[workspace]
EOF

# The program README.md and docs/usage.md both open with, so the dependency list they print is the
# one that compiles rather than the one someone remembered. It never reaches a provider — building
# a module makes no call — so this stays a build with no network in it.
cat > "$WORK/src/main.rs" <<'EOF'
use dsrust::lm::{LM, configure};
use dsrust::signature::SignatureSpec;
use dsrust::{Signature, call, chain_of_thought, predict};

#[derive(Signature)]
/// Answer the question.
struct QA {
    #[input]
    question: String,
    #[output]
    answer: String,
}

#[derive(Signature)]
/// Give the steps.
struct Steps {
    #[input]
    topic: String,
    /// A non-scalar output, which is where a caller would otherwise owe `schemars`.
    #[output]
    steps: Vec<String>,
}

#[dsrust::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    configure(LM::new("openai/gpt-4o-mini")?);

    // Declared and built, not asked: `predict!` reaches no provider, so this needs no key.
    let _ = predict!(QA);
    let _ = chain_of_thought!(QA);
    let _ = predict!(Steps);
    let _ = predict!("question -> answer");
    if false {
        let out = call!(predict!(QA), question = "What is the capital of France?").await?;
        println!("{}", out.answer);
    }

    assert_eq!(QA::signature().instructions, "Answer the question.");
    println!("{}", Steps::signature().outputs.len());
    Ok(())
}
EOF

echo "==> A crate depending only on dsrust"
# Warnings are failures here, because the ones this catches are in the *caller's* crate: a declared
# signature is never constructed, so without help every field of every signature reads as dead code
# in someone else's build.
#
# Its own workspace, but the repo's build directory: a second one costs 1.6 GB of the same
# artifacts. The gates run in sequence, so nothing else is writing there.
( cd "$WORK" && CARGO_TARGET_DIR="$ROOT/target" RUSTFLAGS="-D warnings" cargo run --quiet )
