#!/usr/bin/env python3
"""Compile every Rust block in the guides, from a crate outside the workspace.

Outside for the same reason `check_external_consumer.sh` is: `extern crate self as dsrust` makes
`::dsrust` resolve inside this repository, and every test here already has serde and schemars, so a
snippet compiled in-tree is compiled with help no reader gets. The dependency list is exactly what
README.md tells someone to install.

What this catches is drift between a guide and the crate, in either direction — an API that changed
under the prose, or prose written for an API that never existed. `use dsrust::{call, predict};` sat
in both guides after `predict!` became `Predict!`.

    ./scripts/check_docs.py
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

from docs_snippets import GUIDES, ROOT, extract, generate

WORK = ROOT / "target" / "docs-snippets"

CARGO_TOML = """\
# Generated by scripts/check_docs.py. The dependency list is the one README.md prints, and nothing
# the workspace would have lent it.
[package]
name = "docs-snippets"
version = "0.0.0"
edition = "2024"

[dependencies]
dsrust = {{ path = "{root}/crates/dsrust" }}
tokio = {{ version = "1", features = ["macros", "rt-multi-thread"] }}
anyhow = "1"

# Its own workspace, so this repository's does not lend it what it never declared.
[workspace]
"""


def write_crate() -> list[str]:
    """Lay out the crate and return what was generated, for the report."""
    shutil.rmtree(WORK, ignore_errors=True)
    (WORK / "src" / "bin").mkdir(parents=True)
    (WORK / "Cargo.toml").write_text(CARGO_TOML.format(root=ROOT))

    # A library, not a binary: a guide's fragment is never called, and `cargo check --lib` says so.
    written = []
    lib = ["//! Generated by scripts/check_docs.py. Every guide is a module here.\n"]
    for guide in GUIDES:
        stem = Path(guide).stem.replace("-", "_").replace(".", "_")
        page, programs = generate(guide)
        (WORK / "src" / f"{stem}.rs").write_text(page)
        lib.append(f"mod {stem};")
        written.append(f"{guide}: {page.count('async fn ') + page.count('// ' + guide)} blocks")
        for number, program in enumerate(programs, start=1):
            # A whole program is a whole program: its own binary, with its own `fn main`.
            name = f"{stem}_program_{number}"
            (WORK / "src" / "bin" / f"{name}.rs").write_text(
                f"//! Generated by scripts/check_docs.py from a whole program in {guide}.\n"
                f"#![allow(unused)]\n\n{program}\n"
            )
            written.append(f"{guide}: a whole program -> src/bin/{name}.rs")
    (WORK / "src" / "lib.rs").write_text("\n".join(lib) + "\n")
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--list", action="store_true", help="print the blocks and stop")
    arguments = parser.parse_args()

    if arguments.list:
        for guide in GUIDES:
            for snippet in extract(guide):
                kind = "program" if snippet.is_program else "items" if snippet.is_items else "statements"
                skipped = " (ignored)" if "ignore" in snippet.tags else ""
                print(f"{guide}:{snippet.line}\t{kind}{skipped}")
        return 0

    print("==> Every Rust block in the guides, compiled outside the workspace")
    for line in write_crate():
        print(f"    {line}")

    # Warnings are failures: an unresolved import or an unused `?` in a guide is a reader's problem.
    # Fragments are allowed to leave a value unused, which `docs_fixtures.rs` states once.
    finished = subprocess.run(
        ["cargo", "check", "--all-targets", "--quiet"],
        cwd=WORK,
        env={**__import__("os").environ, "CARGO_TARGET_DIR": str(ROOT / "target"), "RUSTFLAGS": "-D warnings"},
    )
    if finished.returncode != 0:
        print(
            "\nA guide does not compile. Each generated block carries the guide and line it came\n"
            f"from as its first comment; the files are under {WORK.relative_to(ROOT)}/src/.\n"
            "Fix the guide, not the generated file.",
            file=sys.stderr,
        )
    return finished.returncode


if __name__ == "__main__":
    sys.exit(main())
