#!/usr/bin/env bash
# Build a crate that depends on `dsrust` and nothing else.
#
# The workspace cannot see what a caller sees. `extern crate self as dsrust` makes `::dsrust`
# resolve inside this repo, every test here already has serde and schemars, and so a derive that
# expands to `::serde::Serialize` compiles perfectly in every test we run and fails for everyone
# else. That is exactly what happened: a real project reported that `#[derive(Signature)]` forced
# it to add serde and serde_json of its own, and no gate here could have caught it.
#
# So the gate is a crate outside the workspace, with one dependency, exercising the surface a
# caller reaches first: derive a signature, build a module from it, read a field back.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$ROOT/target/external-consumer"

mkdir -p "$WORK/src"
cat > "$WORK/Cargo.toml" <<EOF
# Generated by scripts/check_external_consumer.sh. The point is the dependency list: exactly what
# README.md tells a reader to install, and nothing the workspace would have lent it.
[package]
name = "external-consumer"
version = "0.0.0"
edition = "2024"

[dependencies]
dsrust = { path = "$ROOT/crates/dsrust" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

# Its own workspace, so the repo's does not lend it dependencies it never declared.
[workspace]
EOF

# What the guides themselves say is `scripts/check_docs.py`'s job: it extracts their blocks and
# compiles them, so no transcription can drift. This program is the part a guide does not print — a
# derived signature *run* rather than type-checked, and a non-scalar output field, which is where a
# caller would otherwise owe `schemars`. It never reaches a provider, so there is no network in it.
cat > "$WORK/src/main.rs" <<'EOF'
use dsrust::lm::{LM, configure};
use dsrust::serde_json::json;
use dsrust::signature::{FieldKind, InField, JsonType, OutField, Signature, SignatureSpec};
use dsrust::{ChainOfThought, Predict, call};

#[derive(Signature)]
/// Answer the question.
struct QA {
    #[input]
    question: String,
    #[output]
    answer: String,
}

#[derive(Signature)]
/// Give the steps.
struct Steps {
    #[input]
    topic: String,
    /// A non-scalar output, which is where a caller would otherwise owe `schemars`.
    #[output]
    steps: Vec<String>,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    configure(LM::new("openai/gpt-4o-mini")?);

    // Declared and built, not asked: `Predict!` reaches no provider, so this needs no key.
    let _ = Predict!(QA);
    let _ = ChainOfThought!(QA);
    let _ = Predict!(Steps);
    let _ = Predict!("question -> answer");
    if false {
        let out = call!(Predict!(QA), question = "What is the capital of France?").await?;
        println!("{}", out.answer);
    }

    assert_eq!(QA::signature().instructions, "Answer the question.");
    println!("{}", Steps::signature().outputs.len());

    // A signature shaped at runtime, which is the case that made this crate's `serde_json`
    // re-export necessary: the surface takes `Value`, and *building* one means `json!`. Written
    // through `dsrust::serde_json` and with no `serde_json` line in this crate's manifest, so it
    // fails to compile the moment that re-export goes away.
    let schema = json!({ "type": "array", "items": { "type": "string" } });
    let runtime = Signature {
        instructions: "List the steps.".into(),
        inputs: vec![InField {
            name: "topic".into(),
            ..Default::default()
        }],
        outputs: vec![OutField {
            name: "steps".into(),
            kind: FieldKind::Json(JsonType::reflected("list[str]", schema.clone())),
            ..Default::default()
        }],
    };
    let _ = dsrust::predict::Predict::from_signature(runtime.clone());
    assert_eq!(runtime.outputs.len(), 1);

    // And reading a `Value` back off a prediction, the other half of the same surface.
    let example = dsrust::example! { topic: "bread", steps: json!(["mix", "bake"]) };
    assert_eq!(example.get("steps").and_then(|v| v.as_array()).map(Vec::len), Some(2));
    Ok(())
}
EOF

echo "==> A crate depending only on dsrust"
# Warnings are failures here, because the ones this catches are in the *caller's* crate: a declared
# signature is never constructed, so without help every field of every signature reads as dead code
# in someone else's build.
#
# Its own workspace, but the repo's build directory: a second one costs 1.6 GB of the same
# artifacts. The gates run in sequence, so nothing else is writing there.
( cd "$WORK" && CARGO_TARGET_DIR="$ROOT/target" RUSTFLAGS="-D warnings" cargo run --quiet )
