#!/usr/bin/env bash
# Build a crate that depends on `dsrust` and nothing else.
#
# The workspace cannot see what a caller sees. `extern crate self as dsrust` makes `::dsrust`
# resolve inside this repo, every test here already has serde and schemars, and so a derive that
# expands to `::serde::Serialize` compiles perfectly in every test we run and fails for everyone
# else. That is exactly what happened: a real project reported that `#[derive(Signature)]` forced
# it to add serde and serde_json of its own, and no gate here could have caught it.
#
# So the gate is a crate outside the workspace, with one dependency, exercising the surface a
# caller reaches first: derive a signature, build a module from it, read a field back.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$ROOT/target/external-consumer"

mkdir -p "$WORK/src"
cat > "$WORK/Cargo.toml" <<EOF
# Generated by scripts/check_external_consumer.sh. The point is the dependency list: one entry.
[package]
name = "external-consumer"
version = "0.0.0"
edition = "2024"

[dependencies]
dsrust = { path = "$ROOT" }

# Its own workspace, so the repo's does not lend it dependencies it never declared.
[workspace]
EOF

cat > "$WORK/src/main.rs" <<'EOF'
//! What a caller writes on their first afternoon, with `dsrust` as their only dependency.
use dsrust::signature::SignatureSpec;
use dsrust::{Signature, chain_of_thought, predict};

#[derive(Signature)]
/// Write independent practice for this lesson step.
struct PracticeForStep {
    #[input]
    learning_goal: String,
    #[input]
    worked_example_problem: String,
    #[output]
    practice_question: String,
    /// A non-scalar output, which is where a caller would otherwise owe `schemars`.
    #[output]
    hints: Vec<String>,
}

fn main() {
    let _ = predict!(PracticeForStep);
    let _ = chain_of_thought!(PracticeForStep);
    let signature = PracticeForStep::signature();
    assert_eq!(signature.inputs.len(), 2);
    assert_eq!(signature.outputs.len(), 2);
    println!("{}", signature.instructions);
}
EOF

echo "==> A crate depending only on dsrust"
# Warnings are failures here, because the ones this catches are in the *caller's* crate: a declared
# signature is never constructed, so without help every field of every signature reads as dead code
# in someone else's build.
( cd "$WORK" && RUSTFLAGS="-D warnings" cargo run --quiet )
