"""Record which code points CPython calls a space, a letter, a digit, alphanumeric.

`json_repair` branches on `char.isspace()`, `isalpha()`, `isalnum()` and `isdigit()` in the places
that decide whether a run of text is a bare object key, a number, or prose — so a reply in Chinese
takes a different path from a reply in English, and getting these wrong diverges on the first
non-ASCII character rather than on some corner case.

Rust's own predicates are not these predicates. `char::is_whitespace` follows the Unicode
White_Space property and so excludes `\\x1c`-`\\x1f`, which CPython calls spaces; `is_alphabetic`
follows Alphabetic, which *includes* combining marks and Nl that `str.isalpha()` excludes. And the
Unicode version differs: `unicode-general-category` 1.1.0 is Unicode 16.0.0 where CPython 3.13 is
15.1.0, so several thousand code points assigned in 16.0 would read as letters here and as
unassigned there.

Measured against `unicodedata.category`, three of the four are exactly a category test and one is
not:

    isalpha  <=> category in Lu Ll Lt Lm Lo                       (0 disagreements)
    isalnum  <=> category in Lu Ll Lt Lm Lo Nd Nl No              (0 disagreements)
    isdigit  <=> category Nd, plus 128 code points with Numeric_Type=Digit (superscripts, ...)
    isspace  <=> 29 code points, hardcoded in CPython

So the tables are ranges rather than a category lookup, and they come from the interpreter that
dspy runs on rather than from a Rust crate's idea of Unicode.

Writes two artifacts, deliberately in different shapes:

  - `src/pychar_data.txt`, the implementation's table, embedded with `include_str!`;
  - `tests/conformance/python_char_classes.json`, the oracle a test re-derives by walking every
    code point through the Rust predicates.

    .venv/bin/python scripts/generate_python_char_tables.py
"""

from __future__ import annotations

import json
import pathlib
import sys
import unicodedata

CRATE = pathlib.Path(__file__).parent.parent / "crates" / "dsrust-json-repair"
DATA = CRATE / "src" / "pychar_data.txt"
FIXTURE = CRATE / "tests" / "conformance" / "python_char_classes.json"

#: Every code point, including the surrogates a `str` may hold and a Rust `char` may not.
LIMIT = 0x110000

PREDICATES = {
    "space": str.isspace,
    "alpha": str.isalpha,
    "digit": str.isdigit,
    "alnum": str.isalnum,
}


def ranges(predicate) -> list[tuple[int, int]]:
    """The code points `predicate` accepts, as inclusive ranges."""
    found: list[tuple[int, int]] = []
    start: int | None = None
    for code_point in range(LIMIT):
        accepted = predicate(chr(code_point))
        if accepted and start is None:
            start = code_point
        elif not accepted and start is not None:
            found.append((start, code_point - 1))
            start = None
    if start is not None:
        found.append((start, LIMIT - 1))
    return found


def as_data(tables: dict[str, list[tuple[int, int]]]) -> str:
    """The table in the form `pychar.rs` reads: one predicate per line, hex range pairs."""
    lines = [
        "# Generated by scripts/generate_python_char_tables.py from CPython "
        f"{sys.version_info.major}.{sys.version_info.minor}, Unicode {unicodedata.unidata_version}.",
        "# One predicate per line: name, then inclusive lo-hi code point ranges in hex.",
    ]
    for name, found in tables.items():
        pairs = " ".join(f"{lo:x}-{hi:x}" for lo, hi in found)
        lines.append(f"{name} {pairs}")
    return "\n".join(lines) + "\n"


def main() -> None:
    tables = {name: ranges(predicate) for name, predicate in PREDICATES.items()}

    # A range table that swallowed a whole plane would pass a "does Rust agree" test while being
    # useless, and one that covered only ASCII would pass every test written in English. Both are
    # the shape this file exists to rule out, so both are refused here rather than left to a reader.
    for name, found in tables.items():
        beyond_ascii = [pair for pair in found if pair[1] > 0x7F]
        if not beyond_ascii:
            raise SystemExit(f"{name} accepts nothing above ASCII — the table would prove nothing")
        covered = sum(hi - lo + 1 for lo, hi in found)
        if covered >= LIMIT // 2:
            raise SystemExit(f"{name} accepts {covered} code points — that is not a class, it is a plane")

    # `isalnum` is the union of the other two classes plus the numerics `isdigit` leaves out, so a
    # table where it is *not* a superset has lost rows somewhere.
    alnum = {code_point for lo, hi in tables["alnum"] for code_point in range(lo, hi + 1)}
    for name in ("alpha", "digit"):
        contained = {code_point for lo, hi in tables[name] for code_point in range(lo, hi + 1)}
        if not contained <= alnum:
            raise SystemExit(f"{name} is not contained in alnum — one of the two tables is wrong")

    DATA.parent.mkdir(parents=True, exist_ok=True)
    DATA.write_text(as_data(tables))
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(
        json.dumps(
            {
                "source": f"CPython {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}",
                "what": (
                    "The code points CPython's str.isspace/isalpha/isdigit/isalnum accept, as "
                    "inclusive ranges. The test walks every code point through the Rust predicate "
                    "and rebuilds these ranges, so a wrong answer anywhere shifts a boundary here."
                ),
                "limit": LIMIT,
                "classes": {name: [list(pair) for pair in found] for name, found in tables.items()},
            },
            indent=1,
        )
        + "\n"
    )
    for name, found in tables.items():
        covered = sum(hi - lo + 1 for lo, hi in found)
        print(f"  {name}: {len(found)} ranges, {covered} code points", file=sys.stderr)
    print(f"  wrote {DATA} and {FIXTURE}", file=sys.stderr)


if __name__ == "__main__":
    main()
