"""Write what `cargo test` observed into `backlog.toml`'s `[status]`.

Every other number in that block is generated by the upstream runner. `rust_tests` had no runner —
the upstream script does not invoke cargo — so it stayed the one field typed by hand, and by the
time anyone counted it was 48 behind. The same failure mode as the block it sits in, one field over.

    cargo test --workspace 2>&1 | python3 scripts/record_rust_tests.py

`scripts/run_rust_gates.sh` is what runs it, so proving a change is what updates the number. A run
with a failing test writes nothing: a count taken mid-red says nothing about what passes.
"""

from __future__ import annotations

import re
import sys

import status

#: Every target prints its own line — unit tests, each integration test, and the doc-tests — so the
#: count is a sum rather than a match.
PASSED = re.compile(r"^test result: ok\. (\d+) passed", re.M)


def counted(output: str) -> int | None:
    """How many tests passed, or None if this output is not a clean run to count."""
    if "test result: FAILED" in output or re.search(r"^error(\[E\d+\])?:", output, re.M):
        return None
    results = PASSED.findall(output)
    return sum(int(passed) for passed in results) if results else None


def main() -> None:
    passing = counted(sys.stdin.read())
    if passing is None:
        print("  rust tests: not recorded (the run was not green)", file=sys.stderr)
        return
    changed = status.record({"rust_tests": passing})
    print(f"  rust tests: {'; '.join(changed) if changed else f'{passing}, unchanged'}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
