"""Where a measured number goes, so no two copies of it can disagree.

`backlog.toml`'s `[status]` is generated from runs. The same figures were once typed by hand into a
prose table as well, and every one of them was wrong by the time anyone read it — 456 Rust tests
against 885, 380 upstream tests against 857, and a strict-xfail backlog called empty while holding
an entry. A number kept in two places drifts in one of them.

So there is one writer. `[status]` is the source, README.md's line is rendered from it, and a
recorder that knows only some of the keys cannot blank the rest: the line is rendered from the
merged block after the write, not from what that recorder happened to observe.
"""

from __future__ import annotations

import pathlib
import re
import tomllib

ROOT = pathlib.Path(__file__).parent.parent
BACKLOG = ROOT / "backlog.toml"
README = ROOT / "README.md"
MANIFEST = ROOT / "scripts" / "upstream_tests.txt"

#: The rendered region in README.md. Everything between the two is this script's output, so an
#: edit made there is lost on the next run rather than silently disagreeing with the plan.
OPEN = "<!-- status: generated by scripts/status.py from backlog.toml [status] -->"
CLOSE = "<!-- /status -->"


def rewrite(text: str, values: dict[str, int]) -> tuple[str, list[str]]:
    """The backlog with `[status]` updated, and which keys actually moved."""
    changed = []
    for key, value in values.items():
        pattern = re.compile(rf"^({re.escape(key)} = )(\d+)$", re.M)
        match = pattern.search(text)
        if match is None:
            continue
        if int(match.group(2)) != value:
            changed.append(f"{key}: {match.group(2)} -> {value}")
        text = pattern.sub(rf"\g<1>{value}", text, count=1)
    return text, changed


def upstream_files() -> int:
    return sum(
        1 for line in MANIFEST.read_text().splitlines() if line.strip() and not line.startswith("#")
    )


def sentence(status: dict[str, int]) -> str:
    """The README's one-line version, for a reader who will not open the plan."""
    return (
        f"Today: **{status['rust_tests']} Rust tests pass**, and "
        f"**{status['upstream_tests_passing']} of DSPy's own**, across "
        f"{status['suites_run']} of its {upstream_files()} test files. "
        f"{status['upstream_tests_crossing']} of those cross into the Rust crate."
    )


def render(path: pathlib.Path, body: str) -> None:
    text = path.read_text()
    region = re.compile(f"{re.escape(OPEN)}.*?{re.escape(CLOSE)}", re.S)
    if region.search(text) is None:
        raise SystemExit(f"{path.name} has no generated status region to write")
    path.write_text(region.sub(f"{OPEN}\n\n{body}\n\n{CLOSE}", text))


def record(values: dict[str, int]) -> list[str]:
    """Write what a run observed, and re-render every view of it. Answers with what moved."""
    text, changed = rewrite(BACKLOG.read_text(), values)
    BACKLOG.write_text(text)
    status = tomllib.loads(text)["status"]
    render(README, sentence(status))
    return changed
