"""Where a measured number goes, so no two copies of it can disagree.

`backlog.toml`'s `[status]` is generated from runs. HANDOFF.md's table said the same things in
prose, typed by hand, and every figure in it was wrong by the time anyone read it — 456 Rust tests
against 885, 380 upstream tests against 857, and a strict-xfail backlog called empty while holding
an entry. A number kept in two places drifts in one of them.

So there is one writer. `[status]` is the source, HANDOFF.md's table is rendered from it, and a
recorder that knows only some of the keys cannot blank the rest: the table is rendered from the
merged block after the write, not from what that recorder happened to observe.
"""

from __future__ import annotations

import pathlib
import re
import tomllib

ROOT = pathlib.Path(__file__).parent.parent
BACKLOG = ROOT / "backlog.toml"
HANDOFF = ROOT / "HANDOFF.md"
MANIFEST = ROOT / "scripts" / "upstream_tests.txt"

#: The rendered region in HANDOFF.md. Everything between the two is this script's output, so an
#: edit made there is lost on the next run rather than silently disagreeing with the plan.
OPEN = "<!-- status: generated by scripts/status.py from backlog.toml [status] -->"
CLOSE = "<!-- /status -->"


def rewrite(text: str, values: dict[str, int]) -> tuple[str, list[str]]:
    """The backlog with `[status]` updated, and which keys actually moved."""
    changed = []
    for key, value in values.items():
        pattern = re.compile(rf"^({re.escape(key)} = )(\d+)$", re.M)
        match = pattern.search(text)
        if match is None:
            continue
        if int(match.group(2)) != value:
            changed.append(f"{key}: {match.group(2)} -> {value}")
        text = pattern.sub(rf"\g<1>{value}", text, count=1)
    return text, changed


def upstream_files() -> int:
    return sum(
        1 for line in MANIFEST.read_text().splitlines() if line.strip() and not line.startswith("#")
    )


def table(status: dict[str, int]) -> str:
    """HANDOFF.md's stand table, as the `[status]` block reads today."""
    rows = [
        ("Rust tests", f"{status['rust_tests']} passing"),
        (
            "Upstream dspy tests",
            f"{status['upstream_tests_passing']} passing, "
            f"{status['upstream_tests_crossing']} crossing into Rust, "
            f"{status['upstream_tests_deciding_signatures']} deciding a signature",
        ),
        (
            "Upstream files run",
            f"{status['suites_run']} of {upstream_files()}, every other one excused by name",
        ),
        ("Strict-xfail backlog", f"{status['xfail_backlog']} entry in `conftest.py`"
                                 if status["xfail_backlog"] == 1
                                 else f"{status['xfail_backlog']} entries in `conftest.py`"),
    ]
    return "\n".join(["| | |", "|---|---|", *(f"| {name} | {value} |" for name, value in rows)])


def render_handoff(status: dict[str, int]) -> None:
    text = HANDOFF.read_text()
    region = re.compile(f"{re.escape(OPEN)}.*?{re.escape(CLOSE)}", re.S)
    if region.search(text) is None:
        raise SystemExit(f"{HANDOFF.name} has no generated status region to write")
    HANDOFF.write_text(region.sub(f"{OPEN}\n\n{table(status)}\n\n{CLOSE}", text))


def record(values: dict[str, int]) -> list[str]:
    """Write what a run observed, and re-render every view of it. Answers with what moved."""
    text, changed = rewrite(BACKLOG.read_text(), values)
    BACKLOG.write_text(text)
    render_handoff(tomllib.loads(text)["status"])
    return changed
