//! The `lm` block of a saved program, byte for byte against the one dspy writes.
//!
//! A compiled program records the model each predictor was pinned to. dspy writes that block, its
//! loader sanitises and rebuilds it, and the README claims a file written here is the file dspy
//! would have written — so the comparison is on the bytes, in dspy's key order, and not on a
//! round-trip through this crate's own serialiser, which would agree with itself.
//!
//! The corpus is generated by running the pinned dspy: `scripts/generate_saved_lm_fixture.py`.

use dsrust::lm::saved;
use dsrust::{ChatModel, LM};
use serde_json::{Map, Value, json};

fn fixture() -> Value {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/conformance/state/saved_lm.json");
    serde_json::from_str(&std::fs::read_to_string(&path).expect("the corpus is committed"))
        .expect("it parses")
}

/// The Rust model a case's `dspy.LM(model, **kwargs)` describes.
fn built(model: &str, kwargs: &Map<String, Value>) -> LM {
    let mut lm = LM::new(model).expect("every case names a provider this crate has");
    if kwargs.get("model_type").and_then(Value::as_str) == Some("responses") {
        lm = lm.openai_responses_api();
    }
    if let Some(cache) = kwargs.get("cache").and_then(Value::as_bool) {
        lm = lm.cache(cache);
    }
    if let Some(retries) = kwargs.get("num_retries").and_then(Value::as_u64) {
        lm = lm.retry(dsrust::lm::Retry::attempts(retries as usize));
    }
    lm.config.temperature = kwargs.get("temperature").and_then(Value::as_f64);
    lm.config.max_tokens = kwargs
        .get("max_tokens")
        .and_then(Value::as_u64)
        .map(|n| n as u32);
    lm
}

/// Every case's block, key for key and in dspy's order.
///
/// `api_base` is the one key deliberately not compared: dspy carries a caller's endpoint in the
/// block and this crate keeps an endpoint on the wire config rather than in `LmConfig`, so the
/// "redirected" case is here for what the *sanitiser* does with it, tested below. Every other key
/// of every other case must match exactly — including `temperature: null`, which a port that only
/// wrote the keys it had set would omit.
#[test]
fn every_block_matches_dspys() {
    let fixture = fixture();
    let mut compared = 0;
    for case in fixture["cases"].as_array().expect("cases") {
        let name = case["name"].as_str().expect("a name");
        let kwargs = case["kwargs"].as_object().expect("kwargs");
        if kwargs.contains_key("api_base") {
            continue;
        }
        let expected = case["block"].as_object().expect("a block");
        let ours = saved::dump(&built(case["model"].as_str().expect("a model"), kwargs));

        assert_eq!(
            ours.keys().collect::<Vec<_>>(),
            expected.keys().collect::<Vec<_>>(),
            "{name}: key order differs from dspy's"
        );
        assert_eq!(
            Value::Object(ours),
            Value::Object(expected.clone()),
            "{name}: the block differs from dspy's"
        );
        compared += 1;
    }
    assert!(compared >= 7, "only {compared} cases compared");
}

/// A saved program never carries a credential, which is what makes one safe to pass around.
///
/// dspy filters `api_key` out of the block. This crate holds four provider keys where dspy holds
/// one, so the filter has four ways to be incomplete rather than one — asserted over the whole
/// block rather than by naming the keys, so a fifth provider added later is covered by this too.
#[test]
fn no_credential_reaches_a_saved_block() {
    let lm = LM::new("openai/gpt-4o-mini")
        .expect("parses")
        .openai_api_key("sk-openai-not-real")
        .anthropic_api_key("sk-ant-not-real")
        .openrouter_api_key("sk-or-not-real")
        .ollama_api_key("ollama-not-real");
    let block = serde_json::to_string(&saved::dump(&lm)).expect("serialises");

    for secret in [
        "sk-openai-not-real",
        "sk-ant-not-real",
        "sk-or-not-real",
        "ollama-not-real",
    ] {
        assert!(
            !block.contains(secret),
            "a credential reached the block: {block}"
        );
    }
    for key in block
        .parse::<Value>()
        .ok()
        .into_iter()
        .flat_map(|v| v.as_object().map(|o| o.keys().cloned().collect::<Vec<_>>()))
        .flatten()
    {
        assert!(!key.contains("api_key"), "the block names {key}");
    }
}

/// A model that cannot describe itself states nothing, which is dspy's `null`.
///
/// `ChatModel::dump_state` is defaulted for this, the same way `BaseLM.dump_state` is overridable:
/// a scripted double has no model name to write, and inventing one would put a model in a saved
/// file that nobody ever configured.
#[test]
fn a_model_that_cannot_describe_itself_writes_null() {
    struct Silent;
    impl ChatModel for Silent {
        fn forward<'a>(
            &'a self,
            _request: &'a dsrust::lm::api::LmRequest,
        ) -> impl Future<Output = anyhow::Result<dsrust::lm::api::LmResponse>> + Send + 'a {
            async { anyhow::bail!("not asked") }
        }
    }
    assert_eq!(ChatModel::dump_state(&Silent), None);
    assert!(ChatModel::dump_state(&LM::new("openai/gpt-4o-mini").expect("parses")).is_some());
}

/// The three keys that decide where a call goes are dropped unless the caller vouches for the file.
#[test]
fn sanitising_drops_the_redirect_and_keeps_the_pin() {
    let fixture = fixture();
    let case = fixture["cases"]
        .as_array()
        .expect("cases")
        .iter()
        .find(|case| case["name"] == "redirected")
        .expect("the corpus carries a redirected case");
    let block = case["block"].as_object().expect("a block");
    assert!(
        block.contains_key("api_base"),
        "the corpus case must carry one"
    );

    let dropped = saved::sanitize(block, false);
    for key in saved::UNSAFE_KEYS {
        assert!(
            !dropped.contains_key(key),
            "{key} survived an untrusted load"
        );
    }
    assert_eq!(
        dropped.get("model"),
        block.get("model"),
        "sanitising must keep the pin — dropping it is the defect this replaced"
    );

    let kept = saved::sanitize(block, true);
    assert_eq!(&kept, block, "a trusted load keeps the block whole");
}

/// A block naming a `BaseLM` subclass is refused with dspy's own message.
///
/// Upstream imports the class when the caller says the file is trusted. A Rust binary has no
/// importer, so both paths refuse — but they refuse differently, and the untrusted one says what
/// dspy says so a reader who searches for the message finds the same explanation.
#[test]
fn a_custom_lm_class_is_refused() {
    let mut block = Map::new();
    block.insert(saved::CLASS_KEY.to_owned(), json!("mypackage.lms.MyLM"));
    block.insert("model".to_owned(), json!("openai/gpt-4o-mini"));

    let Err(refused) = saved::rebuild(&block, false) else {
        panic!("must not load a custom class");
    };
    assert!(
        refused
            .to_string()
            .contains("Refusing to import custom serialized LM class"),
        "the message should be upstream's: {refused}"
    );
    assert!(
        saved::rebuild(&block, true).is_err(),
        "trusting the file does not give Rust a Python importer"
    );

    block.insert(saved::CLASS_KEY.to_owned(), json!(saved::BUILTIN_CLASS));
    assert!(
        saved::rebuild(&block, false).is_ok(),
        "dspy's own class loads"
    );
}

/// What a block says is what a rebuilt model says, so the pin survives a load and a save.
///
/// The property that `saved-lm-round-trip` was filed for. Asserted over the corpus rather than one
/// case, because the reasoning-model families reorder the block and a single case would not see it.
#[test]
fn a_block_survives_being_rebuilt() {
    let fixture = fixture();
    let mut checked = 0;
    for case in fixture["cases"].as_array().expect("cases") {
        let name = case["name"].as_str().expect("a name");
        let block = case["block"].as_object().expect("a block");
        let sanitized = saved::sanitize(block, false);
        let rebuilt = saved::rebuild(&sanitized, false)
            .unwrap_or_else(|error| panic!("{name} should rebuild: {error}"));

        assert_eq!(
            Value::Object(saved::dump(&rebuilt)),
            Value::Object(sanitized.clone()),
            "{name}: the block changed on the way through"
        );
        checked += 1;
    }
    assert_eq!(checked, 9, "every corpus case should round-trip");
}
