//! Every custom type reads the shapes dspy's `validate_input` reads, and refuses in dspy's words.
//!
//! Upstream runs `validate_input` as a `mode="before"` validator, so it runs on every construction
//! — including parsing a model's reply. Which shapes it accepts is therefore part of the wire
//! contract: a reply arriving as a bare string where the field is a `Reasoning` is a reply dspy
//! reads, and a port that only accepts the struct form drops it.
//!
//! The golden is generated by running the pinned dspy, never transcribed —
//! `scripts/generate_type_coercion_fixture.py`.

use std::fmt::Write as _;

use dsrust::adapter::types::{Citations, Code, Document, Reasoning, ToolCallResults, ToolCalls};
use dsrust::{Audio, File};
use serde::de::DeserializeOwned;
use serde_json::Value;

/// What one type did with one shape, in the golden's own vocabulary.
fn attempt<T: DeserializeOwned>(input: &Value) -> Result<(), String> {
    serde_json::from_value::<T>(input.clone())
        .map(|_| ())
        .map_err(|error| error.to_string())
}

fn run(type_name: &str, input: &Value) -> Result<(), String> {
    match type_name {
        "Audio" => attempt::<Audio>(input),
        "File" => attempt::<File>(input),
        "Code" => attempt::<Code>(input),
        "Citations" => attempt::<Citations>(input),
        "Document" => attempt::<Document>(input),
        "Reasoning" => attempt::<Reasoning>(input),
        "ToolCalls" => attempt::<ToolCalls>(input),
        "ToolCallResults" => attempt::<ToolCallResults>(input),
        other => panic!("the golden names a type this test does not run: {other}"),
    }
}

#[test]
fn every_type_reads_what_dspy_reads() {
    let fixture: Value =
        serde_json::from_str(include_str!("conformance/adapter/type_coercion.json"))
            .expect("the golden parses");
    let types = fixture["types"].as_object().expect("a map of types");

    let mut wrong = String::new();
    for (type_name, cases) in types {
        for case in cases.as_array().expect("a list of cases") {
            let input = &case["input"];
            let accepted = case["accepted"].as_bool().expect("accepted is a bool");
            let shape = serde_json::to_string(input).expect("the input re-serializes");
            match (run(type_name, input), accepted) {
                (Ok(()), true) => {}
                (Ok(()), false) => {
                    let _ = writeln!(wrong, "  {type_name} accepted {shape}, dspy refused it");
                }
                (Err(error), true) => {
                    let _ = writeln!(wrong, "  {type_name} refused {shape}: {error}");
                }
                (Err(error), false) => {
                    // A null refusal is pydantic's own structural complaint, which describes a
                    // Python type system rather than anything this crate could say. Refusing is
                    // the whole of what the golden asserts there.
                    let Some(expected) = case["refusal"].as_str() else {
                        continue;
                    };
                    if error != expected {
                        let _ = writeln!(
                            wrong,
                            "  {type_name} refused {shape} saying\n      {error}\n    dspy says\n      {expected}"
                        );
                    }
                }
            }
        }
    }
    assert!(
        wrong.is_empty(),
        "shapes read differently from dspy:\n{wrong}"
    );
}
