//! What a `Flex` says about itself, in the several forms its readers need.
//!
//! Split from the module itself because the two change for different reasons: `flex.rs` is what a
//! `Flex` *is* — its state, its binding, its forward — and this is what it *renders*. Three of these
//! go to different readers and are not interchangeable: `signature_string` is the parseable form the
//! generated code embeds, `signature_spec` is the same signature spelled out for a *model*, and
//! `baseline_src` is the module a `Flex` starts as.
//!
//! All of it is held to `tests/conformance/predict/flex.json`, generated by running dspy.

use super::Flex;
use anyhow::{Result, bail};

/// What the code proposer is told about the sandbox, in upstream's words.
const SANDBOX_NOTE: &str = "This module runs in a sandbox: only the tools listed above may be passed to dspy.ReAct/dspy.RLM (their functions live on the host). A function you define inside the module can be called directly in forward, but cannot be handed to those predictors.";

impl Flex {
    /// dspy's `render_signature_string`: the signature back as `"in: T, in2 -> out: T2"`.
    ///
    /// Every field carries its annotation, so a signature parsed from bare names renders with the
    /// `str` the parse gave them — `"question -> answer"` comes back as `"question: str -> answer: str"`.
    pub fn signature_string(&self) -> String {
        let inputs: Vec<String> = self
            .signature
            .inputs
            .iter()
            .map(|field| format!("{}: {}", field.name, field.annotation()))
            .collect();
        let outputs: Vec<String> = self
            .signature
            .outputs
            .iter()
            .map(|field| format!("{}: {}", field.name, field.annotation()))
            .collect();
        format!("{} -> {}", inputs.join(", "), outputs.join(", "))
    }

    /// dspy's `_class_name`: the generated class, named after the signature.
    pub fn class_name(&self) -> String {
        let base = match is_identifier(&self.name) {
            true => self.name.as_str(),
            false => "Flex",
        };
        format!("{base}Module")
    }

    /// dspy's `render_signature_spec`: the signature spelled out for the code proposer.
    ///
    /// Not [`signature_string`](Self::signature_string), which is the parseable form the *generated
    /// code* embeds. This is the form a *model* reads: the name, the objective, and each field on
    /// its own line with its type and description.
    ///
    /// A description is printed unless it is dspy's own `${field}` placeholder, which upstream fills
    /// in for a field nobody described. A signature parsed here carries an empty description in that
    /// case rather than the placeholder, so both spellings of "nobody said" are skipped.
    pub fn signature_spec(&self) -> String {
        let render = |fields: &[(String, String, String)]| match fields.is_empty() {
            true => "  (none)".to_owned(),
            false => fields
                .iter()
                .map(|(name, annotation, desc)| {
                    let described = !desc.is_empty() && !desc.starts_with("${");
                    match described {
                        true => format!("  - {name}: {annotation}  -- {desc}"),
                        false => format!("  - {name}: {annotation}"),
                    }
                })
                .collect::<Vec<_>>()
                .join("\n"),
        };
        let inputs: Vec<_> = self
            .signature
            .inputs
            .iter()
            .map(|field| (field.name.clone(), field.annotation(), field.desc.clone()))
            .collect();
        let outputs: Vec<_> = self
            .signature
            .outputs
            .iter()
            .map(|field| (field.name.clone(), field.annotation(), field.desc.clone()))
            .collect();
        format!(
            "Signature: {}\nObjective (docstring): {}\nInput fields:\n{}\nOutput fields:\n{}\n",
            self.name,
            self.signature.instructions,
            render(&inputs),
            render(&outputs),
        )
    }

    /// dspy's `render_context_blurb`: the tools in scope, and what the sandbox allows.
    ///
    /// A tool's line is the first line of its description, stripped — upstream reads `tool.desc` or
    /// the function's docstring and takes `splitlines()[0]`, so a second line never reaches the
    /// prompt and a tool with nothing to say keeps its trailing space.
    ///
    /// `(no extra context)` when there is nothing to say, which is not cosmetic: the code proposer's
    /// own instructions branch on that exact string.
    pub fn context_blurb(&self, sandboxed: bool) -> String {
        let mut parts = Vec::new();
        if !self.tools.is_empty() {
            let lines: Vec<String> = self
                .tools
                .iter()
                .map(|tool| {
                    let described = tool.description().trim();
                    let first = described.lines().next().unwrap_or_default().trim();
                    format!("  - {}: {first}", tool.name())
                })
                .collect();
            parts.push(format!(
                "Available tools (in scope by name):\n{}",
                lines.join("\n")
            ));
        }
        if sandboxed {
            parts.push(SANDBOX_NOTE.to_owned());
        }
        match parts.is_empty() {
            true => "(no extra context)".to_owned(),
            false => parts.join("\n\n"),
        }
    }

    /// dspy's `_baseline_src`: one predictor over the whole signature, wrapped in a module.
    ///
    /// An `RLM` when tools were given, so the baseline can call them, and a `Predict` otherwise.
    /// The signature always arrives as `dspy.Signature(string, instructions)` rather than as a bare
    /// string, because dspy writes default instructions for a signature nobody wrote any for — the
    /// branch upstream keeps for empty instructions is unreachable from a parsed signature.
    pub(super) fn baseline_src(&self) -> String {
        let returns: Vec<String> = self
            .signature
            .outputs
            .iter()
            .map(|field| format!("{}=result.{}", field.name, field.name))
            .collect();
        let signature = python_repr(&self.signature_string());
        let sig_arg = match self.signature.instructions.trim().is_empty() {
            true => signature,
            false => format!(
                "dspy.Signature({signature}, {})",
                python_repr(self.signature.instructions.trim())
            ),
        };
        let (attr, ctor) = match self.tools.is_empty() {
            true => ("predict", format!("dspy.Predict({sig_arg})")),
            false => {
                let names: Vec<&str> = self.tools.iter().map(|tool| tool.name()).collect();
                (
                    "rlm",
                    format!("dspy.RLM({sig_arg}, tools=[{}])", names.join(", ")),
                )
            }
        };
        format!(
            "class {}(dspy.Module):\n\
             \x20   def __init__(self):\n\
             \x20       super().__init__()\n\
             \x20       self.{attr} = {ctor}\n\
             \n\
             \x20   def forward(self, **inputs):\n\
             \x20       result = self.{attr}(**inputs)\n\
             \x20       return dspy.Prediction({})",
            self.class_name(),
            returns.join(", ")
        )
    }
}

/// dspy's `parse_module_class_name`: the generated module's class, read out of the source.
///
/// Upstream parses with `ast` and prefers the first class defining `forward`, falling back to the
/// first class at all. Reproduced as a scan because the shape is fixed — a module-level `class` line
/// and a `def forward` indented under it — and a Python parser is not something this crate carries.
pub fn class_name_of(module_src: &str) -> Result<String> {
    let mut classes: Vec<(String, bool)> = Vec::new();
    for line in module_src.lines() {
        if let Some(rest) = line.strip_prefix("class ") {
            let name: String = rest
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                classes.push((name, false));
            }
        } else if line.trim_start().starts_with("def forward(")
            && line.starts_with(char::is_whitespace)
            && let Some(last) = classes.last_mut()
        {
            last.1 = true;
        }
    }
    let chosen = classes
        .iter()
        .find(|(_, has_forward)| *has_forward)
        .or_else(|| classes.first());
    match chosen {
        Some((name, _)) => Ok(name.clone()),
        None => bail!("module_src must define a dspy.Module subclass with a `forward` method"),
    }
}

/// Python's `str.isidentifier`, which is what upstream refuses a tool name by.
///
/// Python's rule is `XID_Start` then `XID_Continue`, and those are derived properties this crate has
/// no table for — `unicode-general-category` gives categories, not `XID_*`. So this is an
/// approximation, and the approximation is *stated* rather than assumed: alphabetic or `_` to start,
/// then alphanumeric, `_`, or a combining mark.
///
/// The mark is there because it was measured. `x` followed by a combining acute is an identifier to
/// Python and was not here, since `char::is_alphanumeric` excludes `Mn` — so a tool name dspy accepts
/// was refused. `it_refuses_the_tool_names_python_refuses` holds all twenty cases that were checked;
/// a twenty-first that parts company would be a real one to find rather than a hypothetical.
pub(super) fn is_identifier(name: &str) -> bool {
    fn continues(character: char) -> bool {
        let category = unicode_general_category::get_general_category(character);
        character.is_alphanumeric() || character == '_' || category.abbreviation().starts_with('M')
    }
    let mut chars = name.chars();
    chars
        .next()
        .is_some_and(|first| first.is_alphabetic() || first == '_')
        && chars.all(continues)
}

/// Python's `repr` of a string, which is what the generated source embeds.
///
/// Single quotes unless the value holds one and no double quote, and **control characters escape**
/// — `\n`, `\t`, `\r` by name and anything else unprintable as `\xNN`. That second half was
/// missing at first, and the generated source is Python that has to parse: a literal newline inside
/// a single-quoted string is an unterminated string, not a long one. A signature with a multi-line
/// docstring produced code the sandbox could not run.
fn python_repr(value: &str) -> String {
    let escaped: String = value
        .chars()
        .map(|character| match character {
            '\\' => "\\\\".to_owned(),
            '\n' => "\\n".to_owned(),
            '\t' => "\\t".to_owned(),
            '\r' => "\\r".to_owned(),
            other if (other as u32) < 0x20 || other as u32 == 0x7f => {
                format!("\\x{:02x}", other as u32)
            }
            other => other.to_string(),
        })
        .collect();
    match (escaped.contains('\''), escaped.contains('"')) {
        (true, false) => format!("\"{escaped}\""),
        (true, true) => format!("'{}'", escaped.replace('\'', "\\'")),
        _ => format!("'{escaped}'"),
    }
}
