//! Python's `mimetypes`, for the suffixes this port meets.
//!
//! A media type picked off a filename reaches the model: inside the `data:` URI an `Image` or a
//! `File` renders as, and as an `input_audio` block's `format`. So it is a prompt byte, and the
//! table is generated from CPython rather than transcribed — `scripts/generate_mimetypes_fixture.py`
//! writes the golden `tests/conformance/mimetypes.json` that the test below re-derives.
//!
//! **This is CPython's *built-in* table, and upstream's own answer is not deterministic.**
//! `mimetypes.guess_type` calls `init()`, which merges `/etc/mime.types` and friends over the
//! shipped table — so on the machine this was generated, six of the suffixes came back differently
//! from what CPython ships: `.flac`, `.m4a` and `.ogg` are absent from the built-in table and
//! present in the system's, and `.aac`, `.opus` and `.xml` disagree outright. Pinning to the
//! built-in answer is the only choice that is the same everywhere; the golden records the
//! disagreements so a caller meeting one knows it is upstream's host-dependence rather than a
//! divergence here.
//!
//! One home rather than one per caller: `legacy.rs` carried a document-only copy of this, whose
//! `.xml` entry was already the built-in answer while dspy on that machine said `application/xml`.

/// A suffix as CPython's shipped table names it, or `None` for one it does not know.
///
/// Matched on the text after the last `.`, lowercased, with any query or fragment cut first — a
/// media type is guessed off URLs as well as paths.
pub(crate) fn guess(path: &str) -> Option<&'static str> {
    let path = path.split(['?', '#']).next().unwrap_or(path);
    let suffix = path.rsplit_once('.')?.1.to_ascii_lowercase();
    Some(match suffix.as_str() {
        "aac" => "audio/aac",
        "bin" => "application/octet-stream",
        "bmp" => "image/bmp",
        "csv" => "text/csv",
        "gif" => "image/gif",
        "htm" | "html" => "text/html",
        "jpeg" | "jpg" => "image/jpeg",
        "json" => "application/json",
        "md" => "text/markdown",
        "mp3" => "audio/mpeg",
        "mp4" => "video/mp4",
        "opus" => "audio/opus",
        "pdf" => "application/pdf",
        "png" => "image/png",
        "svg" => "image/svg+xml",
        "tiff" => "image/tiff",
        "txt" => "text/plain",
        "wasm" => "application/wasm",
        "wav" => "audio/x-wav",
        "webm" => "video/webm",
        "webp" => "image/webp",
        "xml" => "text/xml",
        "zip" => "application/zip",
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every entry, against CPython's own answer. Generated by running the interpreter, so the
    /// table cannot drift from it by a typo — which is the failure a hand-written map has.
    #[test]
    fn every_suffix_is_the_one_cpython_ships() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/conformance/constants/mimetypes.json");
        let text = std::fs::read_to_string(&path).expect("the mimetypes golden is committed");
        let golden: serde_json::Value = serde_json::from_str(&text).expect("the golden parses");
        let types = golden["types"].as_object().expect("types");
        assert!(!types.is_empty(), "the golden records no suffixes");

        for (suffix, expected) in types {
            let expected = expected.as_str().expect("a media type");
            assert_eq!(
                guess(&format!("resource{suffix}")),
                Some(expected),
                "for {suffix}"
            );
        }
    }

    /// The suffixes where dspy's answer depends on the host, kept visible: a caller meeting one is
    /// meeting upstream's non-determinism rather than a divergence to file.
    #[test]
    fn the_host_dependent_suffixes_are_recorded_rather_than_resolved() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/conformance/constants/mimetypes.json");
        let text = std::fs::read_to_string(&path).expect("the mimetypes golden is committed");
        let golden: serde_json::Value = serde_json::from_str(&text).expect("the golden parses");
        let differing = golden["machine_specific"]
            .as_object()
            .expect("machine_specific");
        // Whatever the generating machine reported, this crate answers with the *built-in* one.
        for (suffix, both) in differing {
            let builtin = both["builtin"].as_str();
            assert_eq!(
                guess(&format!("resource{suffix}")),
                builtin,
                "for {suffix}, which the generating host spelled {}",
                both["this_machine"]
            );
        }
    }

    /// Guessed off a URL as well as a path, so a query string does not eat the suffix.
    #[test]
    fn a_query_or_fragment_is_cut_before_the_suffix() {
        assert_eq!(guess("https://e.com/a.png?v=2"), Some("image/png"));
        assert_eq!(guess("https://e.com/a.png#top"), Some("image/png"));
        assert_eq!(guess("https://e.com/a.PNG"), Some("image/png"));
        assert_eq!(guess("https://e.com/no-suffix"), None);
        assert_eq!(
            guess("archive.tar.zst"),
            None,
            "an unknown suffix is unknown"
        );
    }
}
